name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-none
          components: rust-src

      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: xorriso nasm clang mtools lld cbindgen
          version: 1.0

      - name: Setup BuildTools
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'

      - name: Build Kernel
        run: xmake build -y

      - uses: actions/upload-artifact@v4
        with:
          name: CoolPotOS
          path: build/CoolPotOS.iso
          compression-level: 9
