name: CI Workflow

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'readme'
      - '.gitignore'
      - 'README.md'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'readme'
      - '.gitignore'
      - 'README.md'

jobs:
  i386:
    runs-on: ubuntu-latest
    name: i386
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Zig
        uses: mlugg/setup-zig@v2

      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: xorriso nasm mtools
          version: 1.0

      - name: Setup xmake
        uses: wenxuanjun/github-action-setup-xmake@master
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          build-cache: true

      - name: Build CoolPotOS-i386
        run: xmake build iso32

      - uses: actions/upload-artifact@v4
        with:
          name: CoolPotOS-i386
          path: build/CoolPotOS.iso
          compression-level: 9

  x86_64:
    runs-on: ubuntu-latest
    name: x86_64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-none
          components: rust-src

      - name: Install oib
        uses: baptiste0928/cargo-install@v3
        with:
          crate: oib

      - name: Install cbindgen
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cbindgen

      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: xorriso clang mtools lld
          version: 1.0

      - name: Setup xmake
        uses: wenxuanjun/github-action-setup-xmake@master
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          build-cache: true

      - name: Build CoolPotOS-x86_64
        run: |
          xmake build iso64
          xmake build img64

      - uses: actions/upload-artifact@v4
        with:
          name: CoolPotOS-x86_64 (ISO)
          path: build/CoolPotOS.iso
          compression-level: 9

      - uses: actions/upload-artifact@v4
        with:
          name: CoolPotOS-x86_64 (IMG)
          path: build/CoolPotOS.img
          compression-level: 9
